#!/bin/bash
# User Status
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-list
mv ./user-list /usr/local/bin/user-list
chmod +x /usr/local/bin/user-list

# instal Buat Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-add
mv ./user-add /usr/bin/buatakun
chmod +x /usr/bin/user-add

# instal Generate Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/generate
mv ./generate /usr/bin/generate
chmod +x /usr/bin/generate

# instal Generate Akun Trial
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/trial
mv ./trial /usr/bin/trial
chmod +x /usr/bin/trial

# instal  Ganti Password Akun SSH/VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/userpass
mv ./userpass /usr/bin/userpass
chmod +x /usr/bin/userpass

# instal Generate Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-renew
mv ./user-renew /usr/bin/userrenew
chmod +x /usr/bin/user-renew

# instal Hapus Akun SSH/OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-delete
mv ./user-delete /usr/bin/user-delete
chmod +x /usr/bin/user-delete

# instal Cek Login Dropbear & OpenSSH
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-login
mv ./user-login /usr/bin/user-login
chmod +x /usr/bin/user-login

# instal Cek Login Dropbear, OpenSSH & OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/master/user-login
mv ./user-login /usr/bin/user-login
chmod +x /usr/bin/user-login

# instal Auto Limit Multi Login
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/auto-limit
mv ./auto-limit /usr/bin/auto-limit
chmod +x /usr/bin/auto-limit

# instal Auto Limit Script Multi Login
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal Melihat detail user SSH & OpenVPN 
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-detail
mv ./user-detail /usr/bin/user-detail
chmod +x /usr/bin/user-detail

# instal Delete Akun Expire
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/delete-user-expire
mv ./delete-user-expire /usr/bin/deleteuserexpire
chmod +x /usr/bin/delete-user-expire

# instal  Kill Multi Login
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/auto-kill-user
mv ./autokilluser /usr/bin/autokilluser
chmod +x /usr/bin/autokilluser

# instal Auto Banned Akun
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/master/user-ban
mv ./user-ban /usr/bin/user-ban
chmod +x /usr/bin/user-ban

# instal Unbanned Akun
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-unban
mv ./user-unban /usr/bin/user-unban
chmod +x /usr/bin/user-unban

# instal Mengunci Akun SSH & OpenVPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-lock
mv ./user-lock /usr/bin/user-lock
chmod +x /usr/bin/userlock

# instal Membuka user SSH & OpenVPN yang terkunci
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-unlock
mv ./userun-lock /usr/bin/user-unlock
chmod +x /usr/bin/userunlock

# instal Melihat daftar user yang terkick oleh perintah user-limit
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/log-limit
mv ./log-limit /usr/bin/loglimit
chmod +x /usr/bin/log-limit

# instal Melihat daftar user yang terbanned oleh perintah user-ban
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/log-ban
mv ./log-ban /usr/bin/log-ban
chmod +x /usr/bin/log-ban

# instal Buat Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-add-pptp
mv ./user-add-pptp /usr/bin/use-radd-pptp
chmod +x /usr/bin/useraddpptp

# instal Hapus Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/user-delete-pptp
mv ./user-delete-pptp /usr/bin/user-delete-pptp
chmod +x /usr/bin/use-rdelete-pptp

# instal Lihat Detail Akun PPTP VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/detailpptp
mv ./detailpptp /usr/bin/detailpptp
chmod +x /usr/bin/detailpptp

# instal Cek login PPTP VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/userloginpptp
mv ./userloginpptp /usr/bin/userloginpptp
chmod +x /usr/bin/userloginpptp

# instal Lihat Daftar User PPTP VPN
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/alluserpptp
mv ./alluserpptp /usr/bin/alluserpptp
chmod +x /usr/bin/alluserpptp

# instal Set Auto Reboot
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/autoreboot
mv ./autoreboot /usr/bin/autoreboot
chmod +x /usr/bin/autoreboot

# Install SPEED tES
apt-get install python
wget https://raw.githubusercontent.com/ehomecore/menu/master/master/speedtest.py
chmod +x speedtest.py

# instal autolimitscript
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/auto-limit-script
mv ./auto-limit-script /usr/bin/auto-limit-script
chmod +x /usr/bin/auto-limit-script

# instal userdelete
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/userdelete
mv ./userdelete /usr/bin/userdelete
chmod +x /usr/bin/userdelete

# Install Menu
cd
wget https://raw.githubusercontent.com/ehomecore/menu/master/menu
mv ./menu /usr/local/bin/menu
chmod +x /usr/local/bin/menu

rm -f /root/iplist.txt

rm -f /root/update

rm -f /root/debian7latest.sh

rm -f /root/debian7latest.sh.x

rm -f /root/ddos-deflate-master.zip

rm -f /root/.bash_history && history -c
